apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: data-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 192.168.2.10
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim
spec:
  storageClassName: data-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  