# Standard Konfiguration fuer einen Kubernetes Master mit host-only Netzwerk
# Einstellungen Master: Anzahl Master Nodes, Anzahl CPU's, reservierter Arbeitsspeicher, Hostname Prefix und DNS Name bei externen Zugriff
master:
  count: 1
  cpus: 2
  memory: 2048
  hostname: master
  dnsname: master.k8s.local
# Einstellungen Worker: Anzahl Worker Nodes, Anzahl CPU's und reservierter Arbeitsspeicher und Hostname Prefix. count: 0 erstellt keine Worker Nodes
worker:
  count: 0
  cpus: 2
  memory: 2048
  hostname: worker
# Kubernetes Einstellungen, u.a. aktuelle Version
k8s:
  version: 1.15.1-00 
# Einstellung ob DHCP zur Festlegung der IP-Adresse verwendet werden soll. Wenn true wird ein Public (bridged) Netzwerk verwendet und ip: und net: Eintraege ignoriert. 
use_dhcp: false  
# Fixe IP Adressen mit welchen die IP fuer Master und Worker beginnen sollen
ip:
  master:   192.168.137.100
  worker:   192.168.137.111
# Netzwerk "private_network" fuer Host-only Netzwerk, "public_network" fuer Bridged Netzwerke
net:
  network_type: private_network
  default_router: ""  
addons:
  # docker, k8s-API, gogs, kanboard, jeninks, Microservices (4x), jupyter (3x), Kubernetes Ingress, docker registry / frontend, nexus3 (repository, docker-group, docker-proxy), mosquitto  
  ports: [ 2376, 6443, 32100, 32200, 32300, 32080, 32090, 32180, 32280, 32088, 32188, 32288, 30443, 32500, 32580, 32511, 32512, 32513, 31883]
  # Repositories mit weiteren Scripts, YAML Dateien etc.
  git: [ "https://github.com/mc-b/misegr.git", "https://github.com/mc-b/duk.git" ]
