kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zones: eu-west-1a, eu-west-1b, eu-west-1c
  fsType: ext4  
reclaimPolicy: Retain
mountOptions:
  - debug
